---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  MOVIEFUN_SERVICE_URL:

inputs:
- name: apps-movie-fun-code

run:
  path: apps-movie-fun-code/ci/tasks/smoke-test.sh